import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import { inter } from "./fonts";
import "./globals.css";
import { FloatingHeader } from "./components/layout/FloatingHeader";
import Footer from "./components/layout/Footer";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${geistMono.variable} antialiased`}>
        <FloatingHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
